services:
    db:
        image: mariadb:10
        command: --default-authentication-plugin=mysql_native_password
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db:/docker-entrypoint-initdb.d
            - englishtips_db:/var/lib/mysql'
    app:
        build: .
        restart: always
        container_name: app
        volumes:
            - .:/var/www/html
            - ./docker/config/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            APP_URL: ${APP_URL}
            DB_DRIVER: ${DB_DRIVER}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USER: ${DB_USER}
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080
volumes:
    englishtips_db:
networks:
    default:
