services:
    db:
        image: mariadb:10
        command: --default-authentication-plugin=mysql_native_password
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/db:/docker-entrypoint-initdb.d
            - scaffold_db:/var/lib/mysql

    composer:
        container_name: composer
        image: scaffold-php-app
        volumes:
        - ./:/var/www/html
        working_dir: /var/www/html
        command: composer install
        depends_on:
            - app

    app:
        image: scaffold-php-app
        build:
            context: ./docker/php/
            args:
                XDEBUG_MODE: ${XDEBUG_MODE}
                XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
                XDEBUG_CLIENT_HOST: ${XDEBUG_CLIENT_HOST}
                XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
        restart: always
        container_name: app
        volumes:
            - .:/var/www/html
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - db
        ports:
            - "80:80"
        environment:
            APP_URL: ${APP_URL}
            DB_DRIVER: ${DB_DRIVER}
            DB_NAME: ${DB_NAME}
            DB_HOST: ${DB_HOST}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_USER: ${DB_USER}
        extra_hosts:
            - "host.docker.internal:host-gateway"
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080
volumes:
    scaffold_db:
networks:
    default:
