DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS reports_url;

CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(200) NOT NULL,
  PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE urls (
	id INT NOT NULL AUTO_INCREMENT,
  short_id VARCHAR(100) NULL,
  url TEXT NOT NULL,
  quantity INT NULL,
  ref_url VARCHAR(100) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE reports_url (
	id INT NOT NULL AUTO_INCREMENT,
  short_id VARCHAR(100) NULL,
  url TEXT NOT NULL,
  comment VARCHAR(100) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE contacts (
	id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NULL,
  email VARCHAR(100) NOT NULL,
  comment VARCHAR(100) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE UNIQUE INDEX short_id_index
ON urls (short_id);

ALTER TABLE urls
ADD deleted_at DATETIME;


ALTER TABLE urls MODIFY short_id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin;
