name: CI CD Prod
on:
  # Keep push disabled for scaffold repos
  # push:
  #   branches:
  #     - main
  # Allow this workflow to be called from other workflows
  workflow_call:
    inputs:
      run_setup_env:
        description: "Run the setup-env job"
        required: false
        type: boolean
        default: true

jobs:
  setup-env:
    name: env
    runs-on: ubuntu-latest
    # Run normally on push/merge; honor input only when called
    if: ${{ github.event_name != 'workflow_call' || inputs.run_setup_env == true }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup environment
        run: touch .env

      - name: Adding values in .env
        run: |
            echo "APP_URL=${{vars.APP_URL}}" >> .env
            echo "DB_DRIVER=${{vars.DB_DRIVER}}" >> .env
            echo "DB_NAME=${{vars.DB_NAME}}" >> .env
            echo "DB_HOST=${{vars.DB_HOST}}" >> .env
            echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
            echo "DB_USER=${{vars.DB_USER}}" >> .env

      # - name: Deploy .env - Sync file
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     local-dir: ./
      #     server: ${{ vars.FTP_HOST }}
      #     username: ${{ vars.FTP_USER }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     server-dir: ${{ vars.FTP_SERVER_DIR }}
