name: Deploy on PR label

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read

jobs:
  deploy:
    if: >-
      github.event.label.name == 'deploy' &&
      github.event.pull_request.state == 'open' &&
      github.base_ref == 'main'
    uses: ./.github/workflows/main.yml
    secrets: inherit

