name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run PHP CodeSniffer
        run: composer phpcs
      - name: Run PHPStan
        run: composer phpstan
      - name: Audit dependencies
        run: composer audit
      - name: Run tests
        run: composer test
